apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gke-disk-claim
  namespace: jenkins
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gke-storage-class
  resources:
    requests:
      storage: 10Gi