apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gke-storage-class
provisioner: pd.csi.storage.gke.io
volumeBindingMode: WaitForFirstConsumer
parameters:
  type: pd-standard
allowVolumeExpansion: true
reclaimPolicy: Delete